import type { PortfolioItemData } from "@/types";

/**
 * 포트폴리오 정적 레지스트리.
 * - 내부 항목: slug = public/portfolio/ 하위 폴더명 (상세페이지 작업)
 * - 외부 항목: externalUrl 지정 (와디즈 펀딩 등). 내부 상세페이지는 생성하지 않음.
 * - displayOrder: 낮을수록 먼저 노출. 새 최상단 작업은 음수 값을 더 낮게 둔다.
 */
export const PORTFOLIO_ITEMS: PortfolioItemData[] = [
  {
    slug: "takmong-wadiz",
    title: "탁몽 · 와디즈 펀딩 상세페이지",
    clientType: "자사 브랜드",
    category: ["상세페이지", "펀딩"],
    industry: "와디즈 펀딩",
    deliverables: ["브랜딩", "기획", "촬영", "상세페이지 디자인"],
    kpi: "펀딩 740% 달성 · 3,701,000원 · 서포터 51명",
    publishedAt: "2026-05-06",
    featured: true,
    tags: ["와디즈", "펀딩성공", "상세페이지"],
    externalUrl: "https://www.wadiz.kr/web/campaign/detail/384334",
    externalLabel: "탁몽 자세히 보기",
    productHref: "/takmong",
  },
  {
    slug: "baby-mat",
    title: "유아매트 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "리빙"],
    industry: "유아/리빙",
    deliverables: ["기획", "디자인", "완성본 납품"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-06-23",
    featured: true,
    tags: ["유아", "상세페이지", "유아매트"],
    displayOrder: -2,
  },
  {
    slug: "baby-hairpin",
    title: "유아 헤어핀 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "패션잡화"],
    industry: "유아/패션잡화",
    deliverables: ["기획", "디자인", "완성본 납품"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-06-23",
    featured: true,
    tags: ["유아", "상세페이지", "헤어핀"],
    displayOrder: -1,
  },
  {
    slug: "cookie",
    title: "쿠키 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "식품"],
    industry: "식품",
    deliverables: ["기획", "디자인", "완성본 납품"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-06-23",
    featured: true,
    tags: ["식품", "상세페이지", "쿠키"],
  },
  {
    slug: "baby-room",
    title: "베이비룸 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "리빙"],
    industry: "유아/리빙",
    deliverables: ["기획", "디자인", "완성본 납품"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-06-23",
    featured: true,
    tags: ["유아", "상세페이지", "베이비룸"],
    displayOrder: -5,
  },
  {
    slug: "strap",
    title: "멀티스트랩 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "리빙"],
    industry: "리빙/잡화",
    deliverables: ["기획", "디자인", "완성본 납품"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-06-23",
    featured: true,
    tags: ["리빙", "상세페이지", "멀티스트랩"],
    displayOrder: -7,
  },
  {
    slug: "tray-cover",
    title: "트레이커버 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "리빙"],
    industry: "리빙/잡화",
    deliverables: ["기획", "디자인", "완성본 납품"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-06-23",
    featured: true,
    tags: ["리빙", "상세페이지", "트레이커버"],
    displayOrder: -6,
  },
  {
    slug: "ricecake",
    title: "순수기정 떡 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "식품"],
    industry: "식품",
    deliverables: ["기획", "디자인", "완성본 납품"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-01-10",
    featured: true,
    tags: ["식품", "상세페이지", "떡"],
  },
  {
    slug: "room-spray",
    title: "룸스프레이 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "리빙"],
    industry: "리빙",
    deliverables: ["기획", "디자인", "완성본 납품"],
    kpi: "브랜드 일관성 확보",
    publishedAt: "2026-01-12",
    featured: true,
    tags: ["리빙", "상세페이지", "룸스프레이"],
  },
  {
    slug: "buckwheat-pillow",
    title: "메밀베개 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "리빙"],
    industry: "리빙",
    deliverables: ["기획", "디자인", "완성본 납품"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-01-15",
    featured: true,
    tags: ["리빙", "상세페이지", "메밀베개"],
    displayOrder: 3,
  },
  {
    slug: "raw-chicken",
    title: "고향맛닭 생닭 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "식품"],
    industry: "식품",
    deliverables: ["기획", "촬영", "디자인", "완성본 납품"],
    kpi: "신규 런칭 전환 최적화",
    publishedAt: "2026-01-18",
    featured: true,
    tags: ["식품", "상세페이지", "생닭"],
  },
  {
    slug: "water-jelly",
    title: "워터젤리 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "식품"],
    industry: "식품",
    deliverables: ["기획", "디자인", "완성본 납품"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-01-20",
    featured: true,
    tags: ["식품", "상세페이지", "워터젤리"],
    displayOrder: -4,
  },
  {
    slug: "baby-bed",
    title: "유아침대 상세페이지",
    clientType: "브랜드 담당자",
    category: ["상세페이지", "리빙"],
    industry: "리빙",
    deliverables: ["기획", "촬영", "디자인", "완성본 납품"],
    kpi: "브랜드 일관성 확보",
    publishedAt: "2026-01-22",
    featured: true,
    tags: ["리빙", "상세페이지", "유아침대"],
    displayOrder: -3,
  },
  {
    slug: "tv-mount",
    title: "티비거치대 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "가전"],
    industry: "가전/리빙",
    deliverables: ["기획", "디자인", "완성본 납품"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-01-25",
    featured: true,
    tags: ["가전", "상세페이지", "티비거치대"],
  },
  {
    slug: "face-towel",
    title: "페이스타월 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "뷰티"],
    industry: "뷰티",
    deliverables: ["기획", "디자인", "완성본 납품"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-01-28",
    featured: true,
    tags: ["뷰티", "상세페이지", "페이스타월"],
  },
  {
    slug: "planner",
    title: "플래너 상세페이지",
    clientType: "브랜드 담당자",
    category: ["상세페이지", "문구"],
    industry: "문구/리빙",
    deliverables: ["기획", "디자인", "완성본 납품"],
    kpi: "브랜드 일관성 확보",
    publishedAt: "2026-02-01",
    featured: true,
    tags: ["문구", "상세페이지", "플래너"],
  },
];
