import type { PortfolioItemData } from "@/types";

/** 9개 포트폴리오 정적 레지스트리 — slug = public/portfolio/ 하위 폴더명 */
export const PORTFOLIO_ITEMS: PortfolioItemData[] = [
  {
    slug: "ricecake",
    title: "순수기정 떡 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "식품"],
    industry: "식품",
    deliverables: ["기획", "디자인", "원본 제공"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-01-10",
    featured: true,
    tags: ["식품", "상세페이지", "떡"],
  },
  {
    slug: "room-spray",
    title: "룸스프레이 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "리빙"],
    industry: "리빙",
    deliverables: ["기획", "디자인", "원본 제공"],
    kpi: "브랜드 일관성 확보",
    publishedAt: "2026-01-12",
    featured: true,
    tags: ["리빙", "상세페이지", "룸스프레이"],
  },
  {
    slug: "buckwheat-pillow",
    title: "메밀배게 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "리빙"],
    industry: "리빙",
    deliverables: ["기획", "디자인", "원본 제공"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-01-15",
    featured: true,
    tags: ["리빙", "상세페이지", "메밀배게"],
  },
  {
    slug: "raw-chicken",
    title: "고향맛닭 생닭 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "식품"],
    industry: "식품",
    deliverables: ["기획", "촬영", "디자인", "원본 제공"],
    kpi: "신규 런칭 전환 최적화",
    publishedAt: "2026-01-18",
    featured: true,
    tags: ["식품", "상세페이지", "생닭"],
  },
  {
    slug: "water-jelly",
    title: "워터젤리 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "식품"],
    industry: "식품",
    deliverables: ["기획", "디자인", "원본 제공"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-01-20",
    featured: true,
    tags: ["식품", "상세페이지", "워터젤리"],
  },
  {
    slug: "baby-bed",
    title: "유아침대 상세페이지",
    clientType: "브랜드 담당자",
    category: ["상세페이지", "리빙"],
    industry: "리빙",
    deliverables: ["기획", "촬영", "디자인", "원본 제공"],
    kpi: "브랜드 일관성 확보",
    publishedAt: "2026-01-22",
    featured: true,
    tags: ["리빙", "상세페이지", "유아침대"],
  },
  {
    slug: "tv-mount",
    title: "티비거치대 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "가전"],
    industry: "가전/리빙",
    deliverables: ["기획", "디자인", "원본 제공"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-01-25",
    featured: true,
    tags: ["가전", "상세페이지", "티비거치대"],
  },
  {
    slug: "face-towel",
    title: "페이스타월 상세페이지",
    clientType: "온라인 셀러",
    category: ["상세페이지", "뷰티"],
    industry: "뷰티",
    deliverables: ["기획", "디자인", "원본 제공"],
    kpi: "구매전환 최적화",
    publishedAt: "2026-01-28",
    featured: true,
    tags: ["뷰티", "상세페이지", "페이스타월"],
  },
  {
    slug: "planner",
    title: "플래너 상세페이지",
    clientType: "브랜드 담당자",
    category: ["상세페이지", "문구"],
    industry: "문구/리빙",
    deliverables: ["기획", "디자인", "원본 제공"],
    kpi: "브랜드 일관성 확보",
    publishedAt: "2026-02-01",
    featured: true,
    tags: ["문구", "상세페이지", "플래너"],
  },
];
